const List = [
    {
      id: "1",
      title: "Acer Aspire 3 AMD 3020e Dual core Processor 14 inches (35.5 cm) Laptop",
      type: "laptop",
   
      price: "50000",
      currency_type: "₹rupee",
      image_url: "https://m.media-amazon.com/images/I/81KoSSAwH2L._SL1500_.jpg",
      
      tags: [
        <span className="word-clr me-2 p-1 px-3">1Y 3M</span>,
        <span className="word-clr me-2 p-1 px-3">Good</span>,
        <span className="word-clr me-2 p-1 px-3">Waranty</span>,
      ],
      created_on: "03-05-2022",
      decription: " hiegt: 15.5inch, width: 20 inch ",
      location: 'dehli',
      rating: '⭐⭐⭐⭐⭐',
      ratingValue: '5',
      
    },
    {
      id: "2",
      title: "Dell Inspiron 3511 Laptop (11th Gen Core i3/ 8GB/ 512GB SSD/ Win11)",
      type: "laptop",
      specification: { ram: "4Gb", processor: "intel core i5 3000" },
      price: "10000",
      currency_type: "₹rupee",
      image_url: "https://m.media-amazon.com/images/I/61Dw5Z8LzJL._SL1000_.jpg",
      // 'tags' : ['today 1k','like new', 'warranty'],
      tags: [
        <span className="word-clr me-2 p-1 px-3">1D 10M</span>,
        <span className="word-clr me-2 p-1 px-3">Good</span>,
        <span className="word-clr me-2 p-1 px-3">Waranty</span>,
      ],
      created_on: "03-05-2022",
      decription: " lorem ipsum",
      location: 'dehli',
      rating: '⭐⭐⭐',
      ratingValue: '3',
    },

    {
      id: "3",
      title: "HP 14s, 11th Gen Intel Core i3, 8GB RAM/512GB SSD 14-inch(35.6 cm)",
      type: "laptop",
      specification: [{ ram: "4Gb", processor: "intel core i5 3000" }],
      price: "10000",
      currency_type: "₹rupee",
      image_url: "https://m.media-amazon.com/images/I/51UdunZimoL._SX569_.jpg",
      tags: [
        <span className="word-clr me-2 p-1 px-3">2Y 3M</span>,
        <span className="word-clr me-2 p-1 px-3">Good</span>,
        <span className="word-clr me-2 p-1 px-3">Waranty</span>,
      ],

      created_on: "03-05-2022",
      decription: "lorem ipsum",
      location: 'pune',
      rating: '⭐⭐⭐⭐',
      ratingValue: '4',
    },
    {
      id: "4",
      title: "Samsung Galaxy S22 Ultra 5G (Burgundy, 12GB, 512GB Storage) ",
      type: "phone",
      specification: { ram: "4Gb", processor: "intel core i5 3000" },
      price: "10000",
      currency_type: "₹rupee",
      image_url:
        "https://images-eu.ssl-images-amazon.com/images/I/31jgoap1cQL._SY445_SX342_QL70_FMwebp_.jpg",
      tags: [
        <span className="word-clr me-2 p-1 px-3">1Y 3M</span>,
        <span className="word-clr me-2 p-1 px-3">Good</span>,
        <span className="word-clr me-2 p-1 px-3">Waranty</span>,
      ],

      created_on: "03-05-2022",
      decription: "lorem ipsum",
      location: 'dehli',
      rating: '⭐',
      ratingValue: '1',
    },
    {
      id: "5",
      title: "Apple iPhone 13 Pro Max (256GB) - Sierra Blue Smart HDR 4, Night mode,",
      type: "phone",
      specification: { ram: "4Gb", processor: "intel core i5 3000" },
      price: "10000",
      currency_type: "₹rupee",
      image_url: "https://m.media-amazon.com/images/I/61-r9zOKBCL._SX679_.jpg",
      tags: [
        <span className="word-clr me-2 p-1 px-3">1Y 3M</span>,
        <span className="word-clr me-2 p-1 px-3">Good</span>,
        <span className="word-clr me-2 p-1 px-3">Waranty</span>,
      ],

      created_on: "03-05-2022",
      decription: "lorem ipsum | Lorem Ipsum",
      location: 'lucknow',
      rating: '⭐⭐⭐⭐⭐',
      ratingValue: '5',
    },
    {
      id: "6",
      title: "Apple iPhone 13 Pro Max (256GB) - Sierra Blue Smart HDR 4, Night mode,",
      type: "phone",
      specification: [{ ram: "4Gb", processor: "intel core i5 3000" }],
      price: "10000",
      currency_type: "₹rupee",
      image_url:
        "https://images-eu.ssl-images-amazon.com/images/I/31tyUh1todL._SY445_SX342_QL70_FMwebp_.jpg",
      tags: [
        <span className="word-clr me-2 p-1 px-3">1Y 3M</span>,
        <span className="word-clr me-2 p-1 px-3">Good</span>,
        <span className="word-clr me-2 p-1 px-3">Waranty</span>,
      ],

      created_on: "03-05-2022",
      decription: "lorem ipsum",
      location: 'lucknow',
      rating: '⭐⭐⭐',
      ratingValue: '3',
    },
    {
      id: "7",
      title: "OnePlus Nord CE 2 Lite 5G (Black Dusk, 6GB RAM, 128GB Storage)",
      type: "phone",
      specification: { ram: "4Gb", processor: "intel core i5 3000" },
      price: "10000",
      currency_type: "₹rupee",
      image_url:
        "https://images-eu.ssl-images-amazon.com/images/I/41ezRvTwcaL._SX300_SY300_QL70_FMwebp_.jpg",
      tags: [
        <span className="word-clr me-2 p-1 px-3">1Y 3M</span>,
        <span className="word-clr me-2 p-1 px-3">Good</span>,
        <span className="word-clr me-2 p-1 px-3">Waranty</span>,
      ],

      created_on: "03-05-2022",
      decription: "lorem ipsum",
      location: 'lucknow',
      rating: '⭐⭐',
      ratingValue: '2',
    },

    {
      id: "8",
      title: "Sony Bravia 80 cm (32 inches) HD Ready Smart LED TV",
      type: "television",
      specification: { ram: "4Gb", processor: "intel core i5 3000" },
      price: "5000",
      currency_type: "₹rupee",
      image_url: "https://m.media-amazon.com/images/I/71vZLIfj5yS._SY450_.jpg",
      tags: [
        <span className="word-clr me-2 p-1 px-3">1Y 3M</span>,
        <span className="word-clr me-2 p-1 px-3">Good</span>,
        <span className="word-clr me-2 p-1 px-3">Waranty</span>,
      ],

      created_on: "03-05-2022",
      decription: "lorem ipsum",
      location: 'pune',
      rating: '⭐⭐',
      ratingValue: '2',
    },

    {
      id: "9",
      title: "LG 108 cm (43 inches) 4K Ultra HD Smart LED TV",
      type: "television",
      specification: { ram: "4Gb", processor: "intel core i5 3000" },
      price: "5000",
      currency_type: "₹rupee",
      image_url: "https://m.media-amazon.com/images/I/71k7M05go-L._SX450_.jpg",
      tags: [
        <span className="word-clr me-2 p-1 px-3">1Y 3M</span>,
        <span className="word-clr me-2 p-1 px-3">Good</span>,
        <span className="word-clr me-2 p-1 px-3">Waranty</span>,
      ],

      created_on: "03-05-2022",
      decription: "lorem ipsum",
      location: 'kanpur',
      rating: '⭐⭐⭐',
      ratingValue: '3',
    },
    {
      id: "10",
      title: "LG 108 cm (43 inches) 4K Ultra HD Smart LED TV",
      type: "television",
      specification: { ram: "4Gb", processor: "intel core i5 3000" },
      price: "15000",
      currency_type: "₹rupee",
      image_url: "https://m.media-amazon.com/images/I/71vZLIfj5yS._SY450_.jpg",
      tags: [
        <span className="word-clr me-2 p-1 px-3">1Y 3M</span>,
        <span className="word-clr me-2 p-1 px-3">Good</span>,
        <span className="word-clr me-2 p-1 px-3">Waranty</span>,
      ],

      created_on: "03-05-2022",
      decription: "lorem ipsum",
      location: 'kanpur',
      rating: '⭐⭐⭐⭐⭐',
      ratingValue: '5',
    },
    {
      id: "11",
      title: "Samsung Galaxy S22 Ultra 5G (Burgundy, 12GB, 512GB Storage) ",
      type: "phone",
      specification: { ram: "4Gb", processor: "intel core i5 3000" },
      price: "10000",
      currency_type: "₹rupee",
      image_url:
        "https://images-eu.ssl-images-amazon.com/images/I/41ezRvTwcaL._SX300_SY300_QL70_FMwebp_.jpg",
      tags: [
        <span className="word-clr me-2 p-1 px-3">1Y 3M</span>,
        <span className="word-clr me-2 p-1 px-3">Good</span>,
        <span className="word-clr me-2 p-1 px-3">Waranty</span>,
      ],

      created_on: "03-05-2022",
      decription: "lorem ipsum",
      location: 'pune',
      rating: '⭐⭐⭐⭐',
      ratingValue: '4',
    },
    {
      id: "12",
      title: "Apple iPhone 13 Pro Max (256GB) - Sierra Blue Smart HDR 4, Night mode,",
      type: "phone",
      specification: { ram: "4Gb", processor: "intel core i5 3000" },
      price: "10000",
      currency_type: "₹rupee",
      image_url:
        "https://images-eu.ssl-images-amazon.com/images/I/31sKeCe8SyL._SX300_SY300_QL70_FMwebp_.jpg",
      tags: [
        <span className="word-clr me-2 p-1 px-3">1Y 3M</span>,
        <span className="word-clr me-2 p-1 px-3">Good</span>,
        <span className="word-clr me-2 p-1 px-3">Waranty</span>,
      ],

      created_on: "03-05-2022",
      decription: "lorem ipsum",
      location: 'dehli',
      rating: '⭐⭐⭐',
      ratingValue: '3',
    },
    {
      id: "13",
      title: "Apple iPhone 13 Pro Max (256GB) - Sierra Blue Smart HDR 4, Night mode,",
      type: "phone",
      specification: [{ ram: "4Gb", processor: "intel core i5 3000" }],
      price: "10000",
      currency_type: "₹rupee",
      image_url:
        "https://images-eu.ssl-images-amazon.com/images/I/41OBf52bnOL._SX300_SY300_QL70_FMwebp_.jpg",
      tags: [
        <span className="word-clr me-2 p-1 px-3">1Y 3M</span>,
        <span className="word-clr me-2 p-1 px-3">Good</span>,
        <span className="word-clr me-2 p-1 px-3">Waranty</span>,
      ],

      created_on: "03-05-2022",
      decription: "lorem ipsum",
      location: 'lucknow',
      rating: '⭐⭐⭐⭐',
      ratingValue: '4',
    },
    {
      id: "14",
      title: "OnePlus Nord CE 2 Lite 5G (Black Dusk, 6GB RAM, 128GB Storage)",
      type: "phone",
      specification: { ram: "4Gb", processor: "intel core i5 3000" },
      price: "10000",
      currency_type: "₹rupee",
      image_url: "https://m.media-amazon.com/images/I/817clKAKcqL._SX679_.jpg",
      tags: [
        <span className="word-clr me-2 p-1 px-3">1Y 3M</span>,
        <span className="word-clr me-2 p-1 px-3">Good</span>,
        <span className="word-clr me-2 p-1 px-3">Waranty</span>,
      ],

      created_on: "03-05-2022",
      decription: "lorem ipsum",
      location: 'dehli',
      rating: '⭐',
      ratingValue: '1',
    },

    {
      id: "15",
      title: "Sony Bravia 80 cm (32 inches) HD Ready Smart LED TV ",
      type: "television",
      specification: { ram: "4Gb", processor: "intel core i5 3000" },
      price: "5000",
      currency_type: "₹rupee",
      image_url: "https://m.media-amazon.com/images/I/71k7M05go-L._SX450_.jpg",
      tags: [
        <span className="word-clr me-2 p-1 px-3 ">1Y 3M</span>,
        <span className="word-clr me-2 p-1 px-3 ">Good</span>,
        <span className="word-clr me-2 p-1 px-3 ">Waranty</span>,
      ],

      created_on: "03-05-2022",
      decription: "lorem ipsum",
      location: 'pune',
      rating: '⭐⭐⭐',
      ratingValue: '3',
    },

    {
      id: "16",
      title: "LG 108 cm (43 inches) 4K Ultra HD Smart LED TV",
      type: "television",
      specification: { ram: "4Gb", processor: "intel core i5 3000" },
      price: "5000",
      currency_type: "₹rupee",
      image_url: "https://m.media-amazon.com/images/I/71YDOppqAzL._SX450_.jpg",
      tags: [
        <span className="word-clr me-2 p-1 px-3">1Y 3M</span>,
        <span className="word-clr me-2 p-1 px-3">Good</span>,
        <span className="word-clr me-2 p-1 px-3">Waranty</span>,
      ],

      created_on: "03-05-2022",
      decription: "lorem ipsum  ",
      location: 'kanpur',
      rating: '⭐⭐⭐⭐⭐',
      ratingValue: '5',
    },
    {
      id: "17",
      title: "LG 108 cm (43 inches) 4K Ultra HD Smart LED TV",
      type: "television",
      specification: { ram: "4Gb", processor: "intel core i5 3000" },
      price: "15000",
      currency_type: "₹rupee",
      image_url: "https://m.media-amazon.com/images/I/61V7cDH8AAS._SX569_.jpg",
      tags: [
        <span className="word-clr me-2 p-1 px-3">1Y 3M</span>,
        <span className="word-clr me-2 p-1 px-3">Good</span>,
        <span className="word-clr me-2 p-1 px-3">Waranty</span>,
      ],

      created_on: "03-05-2022",
      decription: "lorem ipsum",
      location: 'lucknow',
      rating: '⭐⭐⭐',
      ratingValue: '3',
    },
    {
      id: "18",
      title: "Dell Inspiron 5518 Laptop (11th Gen Core i5/ 16GB/ 512GB SSD/ Win10)",
      type: "laptop",
      specification: { ram: "4Gb", processor: "intel core i5 3000" },
      price: "10000",
      currency_type: "₹rupee",
      image_url: "https://m.media-amazon.com/images/I/61Dw5Z8LzJL._SL1000_.jpg",
      // 'tags' : ['today 1k','like new', 'warranty'],
      tags: [
        <span className="word-clr me-2 p-1 px-3">1D 10M</span>,
        <span className="word-clr me-2 p-1 px-3">Good</span>,
        <span className="word-clr me-2 p-1 px-3">Waranty</span>,
      ],

      created_on: "03-05-2022",
      decription: " lorem ipsum",
      location: 'dehli',
      rating: '⭐⭐⭐',
      ratingValue: '3',
    },

    {
      id: "19",
      title: "HP 14s, 11th Gen Intel Core i3, 8GB RAM/512GB SSD 14-inch(35.6 cm)",
      type: "laptop",
      specification: { ram: "4Gb", processor: "intel core i5 3000" },
      price: "10000",
      currency_type: "₹rupee",
      image_url: "https://m.media-amazon.com/images/I/51UdunZimoL._SX569_.jpg",
      tags: [
        <span className="word-clr me-2 p-1 px-3">2Y 3M</span>,
        <span className="word-clr me-2 p-1 px-3">Good</span>,
        <span className="word-clr me-2 p-1 px-3">Waranty</span>,
      ],

      created_on: "03-05-2022",
      decription: "lorem ipsum",
      location: 'pune',
      rating: '⭐⭐⭐⭐⭐',
      ratingValue: '5',
    },
    {
      id: "20",
      title: "Samsung Galaxy S22 Ultra 5G (Burgundy, 12GB, 512GB Storage) ",
      type: "phone",
      specification: { ram: "4Gb", processor: "intel core i5 3000" },
      price: "10000",
      currency_type: "₹rupee",
      image_url:
        "https://images-eu.ssl-images-amazon.com/images/I/31jgoap1cQL._SY445_SX342_QL70_FMwebp_.jpg",
      tags: [
        <span className="word-clr me-2 p-1 px-3">1Y 3M</span>,
        <span className="word-clr me-2 p-1 px-3">Good</span>,
        <span className="word-clr me-2 p-1 px-3">Waranty</span>,
      ],

      created_on: "03-05-2022",
      decription: "lorem ipsum",
      location: 'kanpur',
      rating: '⭐⭐⭐⭐⭐',
      ratingValue: '5',
    },
    {
      id: "21",
      title: "Apple iPhone 13 Pro Max (256GB) - Sierra Blue Smart HDR 4, Night mode,",
      type: "phone",
      specification: { ram: "4Gb", processor: "intel core i5 3000" },
      price: "10000",
      currency_type: "₹rupee",
      image_url: "https://m.media-amazon.com/images/I/61-r9zOKBCL._SX679_.jpg",
      tags: [
        <span className="word-clr me-2 p-1 px-3">1Y 3M</span>,
        <span className="word-clr me-2 p-1 px-3">Good</span>,
        <span className="word-clr me-2 p-1 px-3">Waranty</span>,
      ],

      created_on: "03-05-2022",
      decription: "lorem ipsum",
      location: 'lucknow',
      rating: '⭐⭐⭐⭐',
      ratingValue: '4',
    },
    {
      id: "22",
      title: "Acer Aspire 3 AMD 3020e Dual core Processor 14 inches (35.5 cm) Laptop",
      type: "laptop",
      specification: { ram: "4Gb", processor: "intel core i5 3000" },
      price: "50000",
      currency_type: "₹rupee",
      image_url: "https://m.media-amazon.com/images/I/81KoSSAwH2L._SL1500_.jpg",
      // 'image_url': '/asset/images/laptop1.png',
      tags: [
        <span className="word-clr me-2 p-1 px-3">1Y 3M</span>,
        <span className="word-clr me-2 p-1 px-3">Good</span>,
        <span className="word-clr me-2 p-1 px-3">Waranty</span>,
      ],
      created_on: "03-05-2022",
      decription: " hiegt: 15.5inch, width: 20 inch ",
      location: 'pune',
      rating: '⭐⭐',
      ratingValue: '2',
    },
    {
      id: "23",
      title: "Dell Inspiron 5518 Laptop (11th Gen Core i5/ 16GB/ 512GB SSD/ Win10)",
      type: "laptop",
      specification: { ram: "4Gb", processor: "intel core i5 3000" },
      price: "10000",
      currency_type: "₹rupee",
      image_url: "https://m.media-amazon.com/images/I/61Dw5Z8LzJL._SL1000_.jpg",
      // 'tags' : ['today 1k','like new', 'warranty'],
      tags: [
        <span className="word-clr me-2 p-1 px-3">1D 10M</span>,
        <span className="word-clr me-2 p-1 px-3">Good</span>,
        <span className="word-clr me-2 p-1 px-3">Waranty</span>,
      ],

      created_on: "03-05-2022",
      decription: " lorem ipsum",
      location: 'lucknow',
      rating: '⭐⭐⭐',
      ratingValue: '3',
    },

    {
      id: "24",
      title: "HP 14s, 11th Gen Intel Core i3, 8GB RAM/512GB SSD 14-inch(35.6 cm)",
      type: "laptop",
      specification: [{ ram: "4Gb", processor: "intel core i5 3000" }],
      price: "10000",
      currency_type: "₹rupee",
      image_url: "https://m.media-amazon.com/images/I/51UdunZimoL._SX569_.jpg",
      tags: [
        <span className="word-clr me-2 p-1 px-3">2Y 3M</span>,
        <span className="word-clr me-2 p-1 px-3">Good</span>,
        <span className="word-clr me-2 p-1 px-3">Waranty</span>,
      ],

      created_on: "03-05-2022",
      decription: "lorem ipsum",
      location: 'lucknow',
      rating: '⭐⭐⭐⭐',
      ratingValue: '4',
    },
    {
      id: "25",
      title: "Samsung Galaxy S22 Ultra 5G (Burgundy, 12GB, 512GB Storage) ",
      type: "phone",
      specification: { ram: "4Gb", processor: "intel core i5 3000" },
      price: "10000",
      currency_type: "₹rupee",
      image_url:
        "https://images-eu.ssl-images-amazon.com/images/I/31jgoap1cQL._SY445_SX342_QL70_FMwebp_.jpg",
      tags: [
        <span className="word-clr me-2 p-1 px-3">1Y 3M</span>,
        <span className="word-clr me-2 p-1 px-3">Good</span>,
        <span className="word-clr me-2 p-1 px-3">Waranty</span>,
      ],

      created_on: "03-05-2022",
      decription: "lorem ipsum",
      location: 'dehli',
      rating: '⭐⭐',
      ratingValue: '2',
    },
    {
      id: "26",
      title: "Apple iPhone 13 Pro Max (256GB) - Sierra Blue Smart HDR 4, Night mode,",
      type: "phone",
      specification: { ram: "4Gb", processor: "intel core i5 3000" },
      price: "10000",
      currency_type: "₹rupee",
      image_url: "https://m.media-amazon.com/images/I/61-r9zOKBCL._SX679_.jpg",
      tags: [
        <span className="word-clr me-2 p-1 px-3">1Y 3M</span>,
        <span className="word-clr me-2 p-1 px-3">Good</span>,
        <span className="word-clr me-2 p-1 px-3">Waranty</span>,
      ],

      created_on: "03-05-2022",
      decription: "lorem ipsum",
      location: 'kanpur',
      rating: '⭐⭐⭐⭐⭐',
      ratingValue: '5',
    },
    {
      id: "27",
      title: "Apple iPhone 13 Pro Max (256GB) - Sierra Blue Smart HDR 4, Night mode,",
      type: "phone",
      specification: [{ ram: "4Gb", processor: "intel core i5 3000" }],
      price: "10000",
      currency_type: "₹rupee",
      image_url:
        "https://images-eu.ssl-images-amazon.com/images/I/31tyUh1todL._SY445_SX342_QL70_FMwebp_.jpg",
      tags: [
        <span className="word-clr me-2 p-1 px-3">1Y 3M</span>,
        <span className="word-clr me-2 p-1 px-3">Good</span>,
        <span className="word-clr me-2 p-1 px-3">Waranty</span>,
      ],

      created_on: "03-05-2022",
      decription: "lorem ipsum",
      location: 'dehli',
      rating: '⭐⭐⭐',
      ratingValue: '3',
    },
    {
      id: "28",
      title: " OnePlus Nord CE 2 Lite 5G (Black Dusk, 6GB RAM, 128GB Storage)",
      type: "phone",
      specification: { ram: "4Gb", processor: "intel core i5 3000" },
      price: "10000",
      currency_type: "₹rupee",
      image_url:
        "https://images-eu.ssl-images-amazon.com/images/I/41ezRvTwcaL._SX300_SY300_QL70_FMwebp_.jpg",
      tags: [
        <span className="word-clr me-2 p-1 px-3">1Y 3M</span>,
        <span className="word-clr me-2 p-1 px-3">Good</span>,
        <span className="word-clr me-2 p-1 px-3">Waranty</span>,
      ],

      created_on: "03-05-2022",
      decription: "lorem ipsum",
      location: 'dehli',
      rating: '⭐⭐⭐',
      ratingValue: '3',
    },

    {
      id: "29",
      title: "Sony Bravia 80 cm (32 inches) HD Ready Smart LED TV ",
      type: "television",
      specification: { ram: "4Gb", processor: "intel core i5 3000" },
      price: "5000",
      currency_type: "₹rupee",
      image_url: "https://m.media-amazon.com/images/I/71vZLIfj5yS._SY450_.jpg",
      tags: [
        <span className="word-clr me-2 p-1 px-3">1Y 3M</span>,
        <span className="word-clr me-2 p-1 px-3">Good</span>,
        <span className="word-clr me-2 p-1 px-3">Waranty</span>,
      ],

      created_on: "03-05-2022",
      decription: "lorem ipsum",
      location: 'dehli',
      rating: '⭐',
      ratingValue: '1',
    },

    {
      id: "30",
      title: "LG 108 cm (43 inches) 4K Ultra HD Smart LED TV",
      type: "television",
      specification: { ram: "4Gb", processor: "intel core i5 3000" },
      price: "5000",
      currency_type: "₹rupee",
      image_url: "https://m.media-amazon.com/images/I/71k7M05go-L._SX450_.jpg",
      tags: [
        <span className="word-clr me-2 p-1 px-3">1Y 3M</span>,
        <span className="word-clr me-2 p-1 px-3">Good</span>,
        <span className="word-clr me-2 p-1 px-3">Waranty</span>,
      ],

      created_on: "03-05-2022",
      decription: "lorem ipsum",
      location: 'dehli',
      rating: '⭐⭐⭐⭐⭐',
      ratingValue: '5',
    },
    {
      id: "31",
      title: "LG 108 cm (43 inches) 4K Ultra HD Smart LED TV",
      type: "television",
      specification: { ram: "4Gb", processor: "intel core i5 3000" },
      price: "15000",
      currency_type: "₹rupee",
      image_url: "https://m.media-amazon.com/images/I/71vZLIfj5yS._SY450_.jpg",
      tags: [
        <span className="word-clr me-2 p-1 px-3">1Y 3M</span>,
        <span className="word-clr me-2 p-1 px-3">Good</span>,
        <span className="word-clr me-2 p-1 px-3">Waranty</span>,
      ],

      created_on: "03-05-2022",
      decription: "lorem ipsum",
      location: 'dehli',
      rating: '⭐⭐⭐⭐',
      ratingValue: '4',
    },
    {
      id: "32",
      title: "Samsung Galaxy S22 Ultra 5G (Burgundy, 12GB, 512GB Storage) ",
      type: "phone",
      specification: { ram: "4Gb", processor: "intel core i5 3000" },
      price: "10000",
      currency_type: "₹rupee",
      image_url:
        "https://images-eu.ssl-images-amazon.com/images/I/41ezRvTwcaL._SX300_SY300_QL70_FMwebp_.jpg",
      tags: [
        <span className="word-clr me-2 p-1 px-3">1Y 3M</span>,
        <span className="word-clr me-2 p-1 px-3">Good</span>,
        <span className="word-clr me-2 p-1 px-3">Waranty</span>,
      ],

      created_on: "03-05-2022",
      decription: "lorem ipsum",
      location: 'dehli',
      rating: '⭐⭐',
      ratingValue: '2',
    },
    {
      id: "33",
      title: "Apple iPhone 13 Pro Max (256GB) - Sierra Blue Smart HDR 4, Night mode,",
      type: "phone",
      specification: { ram: "4Gb", processor: "intel core i5 3000" },
      price: "10000",
      currency_type: "₹rupee",
      image_url:
        "https://images-eu.ssl-images-amazon.com/images/I/31sKeCe8SyL._SX300_SY300_QL70_FMwebp_.jpg",
      tags: [
        <span className="word-clr me-2 p-1 px-3">1Y 3M</span>,
        <span className="word-clr me-2 p-1 px-3">Good</span>,
        <span className="word-clr me-2 p-1 px-3">Waranty</span>,
      ],

      created_on: "03-05-2022",
      decription: "lorem ipsum",
      location: 'kanpur',
      rating: '⭐⭐⭐',
      ratingValue: '3',
    },
    {
      id: "34",
      title: " Apple iPhone 13 Pro Max (256GB) - Sierra Blue Smart HDR 4, Night mode,",
      type: "phone",
      specification: [{ ram: "4Gb", processor: "intel core i5 3000" }],
      price: "10000",
      currency_type: "₹rupee",
      image_url:
        "https://images-eu.ssl-images-amazon.com/images/I/41OBf52bnOL._SX300_SY300_QL70_FMwebp_.jpg",
      tags: [
        <span className="word-clr me-2 p-1 px-3">1Y 3M</span>,
        <span className="word-clr me-2 p-1 px-3">Good</span>,
        <span className="word-clr me-2 p-1 px-3">Waranty</span>,
      ],

      created_on: "03-05-2022",
      decription: "lorem ipsum",
      location: 'kanpur',
      rating: '⭐⭐',
      ratingValue: '2',
    },
    {
      id: "35",
      title: "OnePlus Nord CE 2 Lite 5G (Black Dusk, 6GB RAM, 128GB Storage)",
      type: "phone",
      specification: { ram: "4Gb", processor: "intel core i5 3000" },
      price: "10000",
      currency_type: "₹rupee",
      image_url: "https://m.media-amazon.com/images/I/817clKAKcqL._SX679_.jpg",
      tags: [
        <span className="word-clr me-2 p-1 px-3">1Y 3M</span>,
        <span className="word-clr me-2 p-1 px-3">Good</span>,
        <span className="word-clr me-2 p-1 px-3">Waranty</span>,
      ],

      created_on: "03-05-2022",
      decription: "lorem ipsum",
      location: 'kanpur',
      rating: '⭐⭐',
      ratingValue: '2',
    },

    {
      id: "36",
      title: "Sony Bravia 80 cm (32 inches) HD Ready Smart LED TV ",
      type: "television",
      specification: { ram: "4Gb", processor: "intel core i5 3000" },
      price: "5000",
      currency_type: "₹rupee",
      image_url: "https://m.media-amazon.com/images/I/71k7M05go-L._SX450_.jpg",
      tags: [
        <span className="word-clr me-2 p-1 px-3 ">1Y 3M</span>,
        <span className="word-clr me-2 p-1 px-3 ">Good</span>,
        <span className="word-clr me-2 p-1 px-3 ">Waranty</span>,
      ],

      created_on: "03-05-2022",
      decription: "lorem ipsum",
      location: 'kanpur',
      rating: '⭐⭐⭐⭐',
      ratingValue: '4',
    },

    {
      id: "37",
      title: "LG tv | Lorem Ipsum",
      type: "television",
      specification: { ram: "4Gb", processor: "intel core i5 3000" },
      price: "5000",
      currency_type: "₹rupee",
      image_url: "https://m.media-amazon.com/images/I/71YDOppqAzL._SX450_.jpg",
      tags: [
        <span className="word-clr me-2 p-1 px-3">1Y 3M</span>,
        <span className="word-clr me-2 p-1 px-3">Good</span>,
        <span className="word-clr me-2 p-1 px-3">Waranty</span>,
      ],

      created_on: "03-05-2022",
      decription: "lorem ipsum  ",
      location: 'kanpur',
      rating: '⭐⭐⭐⭐⭐',
      ratingValue: '5',
    },
    {
      id: "38",
      title: "LG 108 cm (43 inches) 4K Ultra HD Smart LED TV",
      type: "television",
      specification: { ram: "4Gb", processor: "intel core i5 3000" },
      price: "15000",
      currency_type: "₹rupee",
      image_url: "https://m.media-amazon.com/images/I/61V7cDH8AAS._SX569_.jpg",
      tags: [
        <span className="word-clr me-2 p-1 px-3">1Y 3M</span>,
        <span className="word-clr me-2 p-1 px-3">Good</span>,
        <span className="word-clr me-2 p-1 px-3">Waranty</span>,
      ],

      created_on: "03-05-2022",
      decription: "lorem ipsum",
      location: 'kanpur',
      rating: '⭐⭐⭐',
      ratingValue: '3',
    },
    {
      id: "39",
      title: "Dell Inspiron 5518 Laptop (11th Gen Core i5/ 16GB/ 512GB SSD/ Win10)",
      type: "laptop",
      specification: { ram: "4Gb", processor: "intel core i5 3000" },
      price: "10000",
      currency_type: "₹rupee",
      image_url: "https://m.media-amazon.com/images/I/61Dw5Z8LzJL._SL1000_.jpg",
      // 'tags' : ['today 1k','like new', 'warranty'],
      tags: [
        <span className="word-clr me-2 p-1 px-3">1D 10M</span>,
        <span className="word-clr me-2 p-1 px-3">Good</span>,
        <span className="word-clr me-2 p-1 px-3">Waranty</span>,
      ],

      created_on: "03-05-2022",
      decription: " lorem ipsum",
      location: 'kanpur',
      rating: '⭐⭐⭐⭐⭐',
      ratingValue: '5',
    },

    {
      id: "40",
      title: "HP 14s, 11th Gen Intel Core i3, 8GB RAM/512GB SSD 14-inch(35.6 cm)",
      type: "laptop",
      specification: { ram: "4Gb", processor: "intel core i5 3000" },
      price: "10000",
      currency_type: "₹rupee",
      image_url: "https://m.media-amazon.com/images/I/51UdunZimoL._SX569_.jpg",
      tags: [
        <span className="word-clr me-2 p-1 px-3">2Y 3M</span>,
        <span className="word-clr me-2 p-1 px-3">Good</span>,
        <span className="word-clr me-2 p-1 px-3">Waranty</span>,
      ],

      created_on: "03-05-2022",
      decription: "lorem ipsum",
      location: 'kanpur',
      rating: '⭐⭐⭐',
      ratingValue: '3',
    },
    {
      id: "41",
      title: "Samsung Galaxy S22 Ultra 5G (Burgundy, 12GB, 512GB Storage) ",
      type: "phone",
      specification: { ram: "4Gb", processor: "intel core i5 3000" },
      price: "10000",
      currency_type: "₹rupee",
      image_url:
        "https://images-eu.ssl-images-amazon.com/images/I/31jgoap1cQL._SY445_SX342_QL70_FMwebp_.jpg",
      tags: [
        <span className="word-clr me-2 p-1 px-3">1Y 3M</span>,
        <span className="word-clr me-2 p-1 px-3">Good</span>,
        <span className="word-clr me-2 p-1 px-3">Waranty</span>,
      ],

      created_on: "03-05-2022",
      decription: "lorem ipsum",
      location: 'kanpur',
      rating: '⭐⭐⭐',
      ratingValue: '3',
    },
    {
      id: "42",
      title: "Apple iPhone 13 Pro Max (256GB) - Sierra Blue Smart HDR 4, Night mode,",
      type: "phone",
      specification: { ram: "4Gb", processor: "intel core i5 3000" },
      price: "10000",
      currency_type: "₹rupee",
      image_url: "https://m.media-amazon.com/images/I/61-r9zOKBCL._SX679_.jpg",
      tags: [
        <span className="word-clr me-2 p-1 px-3">1Y 3M</span>,
        <span className="word-clr me-2 p-1 px-3">Good</span>,
        <span className="word-clr me-2 p-1 px-3">Waranty</span>,
      ],

      created_on: "03-05-2022",
      decription: "lorem ipsum",
      location: 'kanpur',
      rating: '⭐⭐⭐⭐⭐',
      ratingValue: '5',
    },
    
    {
      id: "43",
      title: "HP 14s, 11th Gen Intel Core i3, 8GB RAM/512GB SSD 14-inch(35.6 cm)",
      type: "laptop",
      specification: { ram: "4Gb", processor: "intel core i5 3000" },
      price: "10000",
      currency_type: "₹rupee",
      image_url: "https://m.media-amazon.com/images/I/51UdunZimoL._SX569_.jpg",
      tags: [
        <span className="word-clr me-2 p-1 px-3">2Y 3M</span>,
        <span className="word-clr me-2 p-1 px-3">Good</span>,
        <span className="word-clr me-2 p-1 px-3">Waranty</span>,
      ],

      created_on: "03-05-2022",
      decription: "lorem ipsum",
      location: 'pune',
      rating: '⭐',
      ratingValue: '1',
    },
    {
      id: "44",
      title: "Sony Bravia 80 cm (32 inches) HD Ready Smart LED TV ",
      type: "television",
      specification: { ram: "4Gb", processor: "intel core i5 3000" },
      price: "5000",
      currency_type: "₹rupee",
      image_url: "https://m.media-amazon.com/images/I/71vZLIfj5yS._SY450_.jpg",
      tags: [
        <span className="word-clr me-2 p-1 px-3">1Y 3M</span>,
        <span className="word-clr me-2 p-1 px-3">Good</span>,
        <span className="word-clr me-2 p-1 px-3">Waranty</span>,
      ],

      created_on: "03-05-2022",
      decription: "lorem ipsum",
      location: 'dehli',
      rating: '⭐⭐',
      ratingValue: '2',
    },
    {
      id: "45",
      title: "Sony Bravia 80 cm (32 inches) HD Ready Smart LED TV",
      type: "television",
      specification: { ram: "4Gb", processor: "intel core i5 3000" },
      price: "5000",
      currency_type: "₹rupee",
      image_url: "https://m.media-amazon.com/images/I/71vZLIfj5yS._SY450_.jpg",
      tags: [
        <span className="word-clr me-2 p-1 px-3">1Y 3M</span>,
        <span className="word-clr me-2 p-1 px-3">Good</span>,
        <span className="word-clr me-2 p-1 px-3">Waranty</span>,
      ],

      created_on: "03-05-2022",
      decription: "lorem ipsum",
      location: 'dehli',
      rating: '⭐⭐',
      ratingValue: '2',
    },
    {
      id: "46",
      title: "Sony Bravia 80 cm (32 inches) HD Ready Smart LED TV ",
      type: "television",
      specification: { ram: "4Gb", processor: "intel core i5 3000" },
      price: "5000",
      currency_type: "₹rupee",
      image_url: "https://m.media-amazon.com/images/I/71vZLIfj5yS._SY450_.jpg",
      tags: [
        <span className="word-clr me-2 p-1 px-3">1Y 3M</span>,
        <span className="word-clr me-2 p-1 px-3">Good</span>,
        <span className="word-clr me-2 p-1 px-3">Waranty</span>,
      ],

      created_on: "03-05-2022",
      decription: "lorem ipsum",
      location: 'dehli',
      rating: '⭐⭐',
      ratingValue: '2',
    },
    {
      id: "47",
      title: "LG 108 cm (43 inches) 4K Ultra HD Smart LED TV",
      type: "television",
      specification: { ram: "4Gb", processor: "intel core i5 3000" },
      price: "5000",
      currency_type: "₹rupee",
      image_url: "https://m.media-amazon.com/images/I/71vZLIfj5yS._SY450_.jpg",
      tags: [
        <span className="word-clr me-2 p-1 px-3">1Y 3M</span>,
        <span className="word-clr me-2 p-1 px-3">Good</span>,
        <span className="word-clr me-2 p-1 px-3">Waranty</span>,
      ],

      created_on: "03-05-2022",
      decription: "lorem ipsum",
      location: 'dehli',
      rating: '⭐⭐',
      ratingValue: '2',
    },
    {
      id: "48",
      title: "Acer Aspire 3 AMD 3020e Dual core Processor 14 inches (35.5 cm) Laptop",
      type: "laptop",
   
      price: "50000",
      currency_type: "₹rupee",
      image_url: "https://m.media-amazon.com/images/I/81KoSSAwH2L._SL1500_.jpg",
      
      tags: [
        <span className="word-clr me-2 p-1 px-3">1Y 3M</span>,
        <span className="word-clr me-2 p-1 px-3">Good</span>,
        <span className="word-clr me-2 p-1 px-3">Waranty</span>,
      ],
      created_on: "03-05-2022",
      decription: " hiegt: 15.5inch, width: 20 inch ",
      location: 'dehli',
      rating: '⭐⭐⭐⭐⭐',
      ratingValue: '5',
      
    },
    {
      id: "49",
      title: "Dell Inspiron 3511 Laptop (11th Gen Core i3/ 8GB/ 512GB SSD/ Win11)",
      type: "laptop",
      specification: { ram: "4Gb", processor: "intel core i5 3000" },
      price: "10000",
      currency_type: "₹rupee",
      image_url: "https://m.media-amazon.com/images/I/61Dw5Z8LzJL._SL1000_.jpg",
      // 'tags' : ['today 1k','like new', 'warranty'],
      tags: [
        <span className="word-clr me-2 p-1 px-3">1D 10M</span>,
        <span className="word-clr me-2 p-1 px-3">Good</span>,
        <span className="word-clr me-2 p-1 px-3">Waranty</span>,
      ],
      created_on: "03-05-2022",
      decription: " lorem ipsum",
      location: 'dehli',
      rating: '⭐⭐⭐',
      ratingValue: '3',
    },

    {
      id: "50",
      title: "HP 14s, 11th Gen Intel Core i3, 8GB RAM/512GB SSD 14-inch(35.6 cm)",
      type: "laptop",
      specification: [{ ram: "4Gb", processor: "intel core i5 3000" }],
      price: "10000",
      currency_type: "₹rupee",
      image_url: "https://m.media-amazon.com/images/I/51UdunZimoL._SX569_.jpg",
      tags: [
        <span className="word-clr me-2 p-1 px-3">2Y 3M</span>,
        <span className="word-clr me-2 p-1 px-3">Good</span>,
        <span className="word-clr me-2 p-1 px-3">Waranty</span>,
      ],

      created_on: "03-05-2022",
      decription: "lorem ipsum",
      location: 'pune',
      rating: '⭐⭐⭐⭐',
      ratingValue: '4',
    },
    {
      id: "51",
      title: "Samsung Galaxy S22 Ultra 5G (Burgundy, 12GB, 512GB Storage) ",
      type: "phone",
      specification: { ram: "4Gb", processor: "intel core i5 3000" },
      price: "10000",
      currency_type: "₹rupee",
      image_url:
        "https://images-eu.ssl-images-amazon.com/images/I/31jgoap1cQL._SY445_SX342_QL70_FMwebp_.jpg",
      tags: [
        <span className="word-clr me-2 p-1 px-3">1Y 3M</span>,
        <span className="word-clr me-2 p-1 px-3">Good</span>,
        <span className="word-clr me-2 p-1 px-3">Waranty</span>,
      ],

      created_on: "03-05-2022",
      decription: "lorem ipsum",
      location: 'dehli',
      rating: '⭐',
      ratingValue: '1',
    },
    {
      id: "52",
      title: "Apple iPhone 13 Pro Max (256GB) - Sierra Blue Smart HDR 4, Night mode,",
      type: "phone",
      specification: { ram: "4Gb", processor: "intel core i5 3000" },
      price: "10000",
      currency_type: "₹rupee",
      image_url: "https://m.media-amazon.com/images/I/61-r9zOKBCL._SX679_.jpg",
      tags: [
        <span className="word-clr me-2 p-1 px-3">1Y 3M</span>,
        <span className="word-clr me-2 p-1 px-3">Good</span>,
        <span className="word-clr me-2 p-1 px-3">Waranty</span>,
      ],

      created_on: "03-05-2022",
      decription: "lorem ipsum | Lorem Ipsum",
      location: 'lucknow',
      rating: '⭐⭐⭐⭐⭐',
      ratingValue: '5',
    },
    {
      id: "53",
      title: "Apple iPhone 13 Pro Max (256GB) - Sierra Blue Smart HDR 4, Night mode,",
      type: "phone",
      specification: [{ ram: "4Gb", processor: "intel core i5 3000" }],
      price: "10000",
      currency_type: "₹rupee",
      image_url:
        "https://images-eu.ssl-images-amazon.com/images/I/31tyUh1todL._SY445_SX342_QL70_FMwebp_.jpg",
      tags: [
        <span className="word-clr me-2 p-1 px-3">1Y 3M</span>,
        <span className="word-clr me-2 p-1 px-3">Good</span>,
        <span className="word-clr me-2 p-1 px-3">Waranty</span>,
      ],

      created_on: "03-05-2022",
      decription: "lorem ipsum",
      location: 'lucknow',
      rating: '⭐⭐⭐',
      ratingValue: '3',
    },
    {
      id: "54",
      title: "OnePlus Nord CE 2 Lite 5G (Black Dusk, 6GB RAM, 128GB Storage)",
      type: "phone",
      specification: { ram: "4Gb", processor: "intel core i5 3000" },
      price: "10000",
      currency_type: "₹rupee",
      image_url:
        "https://images-eu.ssl-images-amazon.com/images/I/41ezRvTwcaL._SX300_SY300_QL70_FMwebp_.jpg",
      tags: [
        <span className="word-clr me-2 p-1 px-3">1Y 3M</span>,
        <span className="word-clr me-2 p-1 px-3">Good</span>,
        <span className="word-clr me-2 p-1 px-3">Waranty</span>,
      ],

      created_on: "03-05-2022",
      decription: "lorem ipsum",
      location: 'lucknow',
      rating: '⭐⭐',
      ratingValue: '2',
    },

    {
      id: "55",
      title: "Sony Bravia 80 cm (32 inches) HD Ready Smart LED TV",
      type: "television",
      specification: { ram: "4Gb", processor: "intel core i5 3000" },
      price: "5000",
      currency_type: "₹rupee",
      image_url: "https://m.media-amazon.com/images/I/71vZLIfj5yS._SY450_.jpg",
      tags: [
        <span className="word-clr me-2 p-1 px-3">1Y 3M</span>,
        <span className="word-clr me-2 p-1 px-3">Good</span>,
        <span className="word-clr me-2 p-1 px-3">Waranty</span>,
      ],

      created_on: "03-05-2022",
      decription: "lorem ipsum",
      location: 'pune',
      rating: '⭐⭐',
      ratingValue: '2',
    },

    {
      id: "56",
      title: "LG 108 cm (43 inches) 4K Ultra HD Smart LED TV",
      type: "television",
      specification: { ram: "4Gb", processor: "intel core i5 3000" },
      price: "5000",
      currency_type: "₹rupee",
      image_url: "https://m.media-amazon.com/images/I/71k7M05go-L._SX450_.jpg",
      tags: [
        <span className="word-clr me-2 p-1 px-3">1Y 3M</span>,
        <span className="word-clr me-2 p-1 px-3">Good</span>,
        <span className="word-clr me-2 p-1 px-3">Waranty</span>,
      ],

      created_on: "03-05-2022",
      decription: "lorem ipsum",
      location: 'kanpur',
      rating: '⭐⭐⭐',
      ratingValue: '3',
    },
    {
      id: "57",
      title: "LG 108 cm (43 inches) 4K Ultra HD Smart LED TV",
      type: "television",
      specification: { ram: "4Gb", processor: "intel core i5 3000" },
      price: "15000",
      currency_type: "₹rupee",
      image_url: "https://m.media-amazon.com/images/I/71vZLIfj5yS._SY450_.jpg",
      tags: [
        <span className="word-clr me-2 p-1 px-3">1Y 3M</span>,
        <span className="word-clr me-2 p-1 px-3">Good</span>,
        <span className="word-clr me-2 p-1 px-3">Waranty</span>,
      ],

      created_on: "03-05-2022",
      decription: "lorem ipsum",
      location: 'kanpur',
      rating: '⭐⭐⭐⭐⭐',
      ratingValue: '5',
    },
    {
      id: "58",
      title: "Samsung Galaxy S22 Ultra 5G (Burgundy, 12GB, 512GB Storage) ",
      type: "phone",
      specification: { ram: "4Gb", processor: "intel core i5 3000" },
      price: "10000",
      currency_type: "₹rupee",
      image_url:
        "https://images-eu.ssl-images-amazon.com/images/I/41ezRvTwcaL._SX300_SY300_QL70_FMwebp_.jpg",
      tags: [
        <span className="word-clr me-2 p-1 px-3">1Y 3M</span>,
        <span className="word-clr me-2 p-1 px-3">Good</span>,
        <span className="word-clr me-2 p-1 px-3">Waranty</span>,
      ],

      created_on: "03-05-2022",
      decription: "lorem ipsum",
      location: 'pune',
      rating: '⭐⭐⭐⭐',
      ratingValue: '4',
    },
    {
      id: "59",
      title: "Apple iPhone 13 Pro Max (256GB) - Sierra Blue Smart HDR 4, Night mode,",
      type: "phone",
      specification: { ram: "4Gb", processor: "intel core i5 3000" },
      price: "10000",
      currency_type: "₹rupee",
      image_url:
        "https://images-eu.ssl-images-amazon.com/images/I/31sKeCe8SyL._SX300_SY300_QL70_FMwebp_.jpg",
      tags: [
        <span className="word-clr me-2 p-1 px-3">1Y 3M</span>,
        <span className="word-clr me-2 p-1 px-3">Good</span>,
        <span className="word-clr me-2 p-1 px-3">Waranty</span>,
      ],

      created_on: "03-05-2022",
      decription: "lorem ipsum",
      location: 'dehli',
      rating: '⭐⭐⭐',
      ratingValue: '3',
    },
    {
      id: "60",
      title: "Apple iPhone 13 Pro Max (256GB) - Sierra Blue Smart HDR 4, Night mode,",
      type: "phone",
      specification: [{ ram: "4Gb", processor: "intel core i5 3000" }],
      price: "10000",
      currency_type: "₹rupee",
      image_url:
        "https://images-eu.ssl-images-amazon.com/images/I/41OBf52bnOL._SX300_SY300_QL70_FMwebp_.jpg",
      tags: [
        <span className="word-clr me-2 p-1 px-3">1Y 3M</span>,
        <span className="word-clr me-2 p-1 px-3">Good</span>,
        <span className="word-clr me-2 p-1 px-3">Waranty</span>,
      ],

      created_on: "03-05-2022",
      decription: "lorem ipsum",
      location: 'lucknow',
      rating: '⭐⭐⭐⭐',
      ratingValue: '4',
    },
    {
      id: "61",
      title: "OnePlus Nord CE 2 Lite 5G (Black Dusk, 6GB RAM, 128GB Storage)",
      type: "phone",
      specification: { ram: "4Gb", processor: "intel core i5 3000" },
      price: "10000",
      currency_type: "₹rupee",
      image_url: "https://m.media-amazon.com/images/I/817clKAKcqL._SX679_.jpg",
      tags: [
        <span className="word-clr me-2 p-1 px-3">1Y 3M</span>,
        <span className="word-clr me-2 p-1 px-3">Good</span>,
        <span className="word-clr me-2 p-1 px-3">Waranty</span>,
      ],

      created_on: "03-05-2022",
      decription: "lorem ipsum",
      location: 'dehli',
      rating: '⭐',
      ratingValue: '1',
    },

    {
      id: "62",
      title: "Sony Bravia 80 cm (32 inches) HD Ready Smart LED TV ",
      type: "television",
      specification: { ram: "4Gb", processor: "intel core i5 3000" },
      price: "5000",
      currency_type: "₹rupee",
      image_url: "https://m.media-amazon.com/images/I/71k7M05go-L._SX450_.jpg",
      tags: [
        <span className="word-clr me-2 p-1 px-3 ">1Y 3M</span>,
        <span className="word-clr me-2 p-1 px-3 ">Good</span>,
        <span className="word-clr me-2 p-1 px-3 ">Waranty</span>,
      ],

      created_on: "03-05-2022",
      decription: "lorem ipsum",
      location: 'pune',
      rating: '⭐⭐⭐',
      ratingValue: '3',
    },

    {
      id: "63",
      title: "LG 108 cm (43 inches) 4K Ultra HD Smart LED TV",
      type: "television",
      specification: { ram: "4Gb", processor: "intel core i5 3000" },
      price: "5000",
      currency_type: "₹rupee",
      image_url: "https://m.media-amazon.com/images/I/71YDOppqAzL._SX450_.jpg",
      tags: [
        <span className="word-clr me-2 p-1 px-3">1Y 3M</span>,
        <span className="word-clr me-2 p-1 px-3">Good</span>,
        <span className="word-clr me-2 p-1 px-3">Waranty</span>,
      ],

      created_on: "03-05-2022",
      decription: "lorem ipsum  ",
      location: 'kanpur',
      rating: '⭐⭐⭐⭐⭐',
      ratingValue: '5',
    },
    {
      id: "64",
      title: "LG 108 cm (43 inches) 4K Ultra HD Smart LED TV",
      type: "television",
      specification: { ram: "4Gb", processor: "intel core i5 3000" },
      price: "15000",
      currency_type: "₹rupee",
      image_url: "https://m.media-amazon.com/images/I/61V7cDH8AAS._SX569_.jpg",
      tags: [
        <span className="word-clr me-2 p-1 px-3">1Y 3M</span>,
        <span className="word-clr me-2 p-1 px-3">Good</span>,
        <span className="word-clr me-2 p-1 px-3">Waranty</span>,
      ],

      created_on: "03-05-2022",
      decription: "lorem ipsum",
      location: 'lucknow',
      rating: '⭐⭐⭐',
      ratingValue: '3',
    },
    {
      id: "65",
      title: "Dell Inspiron 5518 Laptop (11th Gen Core i5/ 16GB/ 512GB SSD/ Win10)",
      type: "laptop",
      specification: { ram: "4Gb", processor: "intel core i5 3000" },
      price: "10000",
      currency_type: "₹rupee",
      image_url: "https://m.media-amazon.com/images/I/61Dw5Z8LzJL._SL1000_.jpg",
      // 'tags' : ['today 1k','like new', 'warranty'],
      tags: [
        <span className="word-clr me-2 p-1 px-3">1D 10M</span>,
        <span className="word-clr me-2 p-1 px-3">Good</span>,
        <span className="word-clr me-2 p-1 px-3">Waranty</span>,
      ],

      created_on: "03-05-2022",
      decription: " lorem ipsum",
      location: 'dehli',
      rating: '⭐⭐⭐',
      ratingValue: '3',
    },

    {
      id: "66",
      title: "HP 14s, 11th Gen Intel Core i3, 8GB RAM/512GB SSD 14-inch(35.6 cm)",
      type: "laptop",
      specification: { ram: "4Gb", processor: "intel core i5 3000" },
      price: "10000",
      currency_type: "₹rupee",
      image_url: "https://m.media-amazon.com/images/I/51UdunZimoL._SX569_.jpg",
      tags: [
        <span className="word-clr me-2 p-1 px-3">2Y 3M</span>,
        <span className="word-clr me-2 p-1 px-3">Good</span>,
        <span className="word-clr me-2 p-1 px-3">Waranty</span>,
      ],

      created_on: "03-05-2022",
      decription: "lorem ipsum",
      location: 'pune',
      rating: '⭐⭐⭐⭐⭐',
      ratingValue: '5',
    },
    {
      id: "67",
      title: "Samsung Galaxy S22 Ultra 5G (Burgundy, 12GB, 512GB Storage) ",
      type: "phone",
      specification: { ram: "4Gb", processor: "intel core i5 3000" },
      price: "10000",
      currency_type: "₹rupee",
      image_url:
        "https://images-eu.ssl-images-amazon.com/images/I/31jgoap1cQL._SY445_SX342_QL70_FMwebp_.jpg",
      tags: [
        <span className="word-clr me-2 p-1 px-3">1Y 3M</span>,
        <span className="word-clr me-2 p-1 px-3">Good</span>,
        <span className="word-clr me-2 p-1 px-3">Waranty</span>,
      ],

      created_on: "03-05-2022",
      decription: "lorem ipsum",
      location: 'kanpur',
      rating: '⭐⭐⭐⭐⭐',
      ratingValue: '5',
    },
    {
      id: "68",
      title: "Apple iPhone 13 Pro Max (256GB) - Sierra Blue Smart HDR 4, Night mode,",
      type: "phone",
      specification: { ram: "4Gb", processor: "intel core i5 3000" },
      price: "10000",
      currency_type: "₹rupee",
      image_url: "https://m.media-amazon.com/images/I/61-r9zOKBCL._SX679_.jpg",
      tags: [
        <span className="word-clr me-2 p-1 px-3">1Y 3M</span>,
        <span className="word-clr me-2 p-1 px-3">Good</span>,
        <span className="word-clr me-2 p-1 px-3">Waranty</span>,
      ],

      created_on: "03-05-2022",
      decription: "lorem ipsum",
      location: 'lucknow',
      rating: '⭐⭐⭐⭐',
      ratingValue: '4',
    },
    {
      id: "69",
      title: "Acer Aspire 3 AMD 3020e Dual core Processor 14 inches (35.5 cm) Laptop",
      type: "laptop",
      specification: { ram: "4Gb", processor: "intel core i5 3000" },
      price: "50000",
      currency_type: "₹rupee",
      image_url: "https://m.media-amazon.com/images/I/81KoSSAwH2L._SL1500_.jpg",
      // 'image_url': '/asset/images/laptop1.png',
      tags: [
        <span className="word-clr me-2 p-1 px-3">1Y 3M</span>,
        <span className="word-clr me-2 p-1 px-3">Good</span>,
        <span className="word-clr me-2 p-1 px-3">Waranty</span>,
      ],
      created_on: "03-05-2022",
      decription: " hiegt: 15.5inch, width: 20 inch ",
      location: 'pune',
      rating: '⭐⭐',
      ratingValue: '2',
    },
    {
      id: "70",
      title: "Dell Inspiron 5518 Laptop (11th Gen Core i5/ 16GB/ 512GB SSD/ Win10)",
      type: "laptop",
      specification: { ram: "4Gb", processor: "intel core i5 3000" },
      price: "10000",
      currency_type: "₹rupee",
      image_url: "https://m.media-amazon.com/images/I/61Dw5Z8LzJL._SL1000_.jpg",
      // 'tags' : ['today 1k','like new', 'warranty'],
      tags: [
        <span className="word-clr me-2 p-1 px-3">1D 10M</span>,
        <span className="word-clr me-2 p-1 px-3">Good</span>,
        <span className="word-clr me-2 p-1 px-3">Waranty</span>,
      ],

      created_on: "03-05-2022",
      decription: " lorem ipsum",
      location: 'lucknow',
      rating: '⭐⭐⭐',
      ratingValue: '3',
    },

    {
      id: "71",
      title: "HP 14s, 11th Gen Intel Core i3, 8GB RAM/512GB SSD 14-inch(35.6 cm)",
      type: "laptop",
      specification: [{ ram: "4Gb", processor: "intel core i5 3000" }],
      price: "10000",
      currency_type: "₹rupee",
      image_url: "https://m.media-amazon.com/images/I/51UdunZimoL._SX569_.jpg",
      tags: [
        <span className="word-clr me-2 p-1 px-3">2Y 3M</span>,
        <span className="word-clr me-2 p-1 px-3">Good</span>,
        <span className="word-clr me-2 p-1 px-3">Waranty</span>,
      ],

      created_on: "03-05-2022",
      decription: "lorem ipsum",
      location: 'lucknow',
      rating: '⭐⭐⭐⭐',
      ratingValue: '4',
    },
    {
      id: "72",
      title: "Samsung Galaxy S22 Ultra 5G (Burgundy, 12GB, 512GB Storage) ",
      type: "phone",
      specification: { ram: "4Gb", processor: "intel core i5 3000" },
      price: "10000",
      currency_type: "₹rupee",
      image_url:
        "https://images-eu.ssl-images-amazon.com/images/I/31jgoap1cQL._SY445_SX342_QL70_FMwebp_.jpg",
      tags: [
        <span className="word-clr me-2 p-1 px-3">1Y 3M</span>,
        <span className="word-clr me-2 p-1 px-3">Good</span>,
        <span className="word-clr me-2 p-1 px-3">Waranty</span>,
      ],

      created_on: "03-05-2022",
      decription: "lorem ipsum",
      location: 'dehli',
      rating: '⭐⭐',
      ratingValue: '2',
    },
    {
      id: "73",
      title: "Apple iPhone 13 Pro Max (256GB) - Sierra Blue Smart HDR 4, Night mode,",
      type: "phone",
      specification: { ram: "4Gb", processor: "intel core i5 3000" },
      price: "10000",
      currency_type: "₹rupee",
      image_url: "https://m.media-amazon.com/images/I/61-r9zOKBCL._SX679_.jpg",
      tags: [
        <span className="word-clr me-2 p-1 px-3">1Y 3M</span>,
        <span className="word-clr me-2 p-1 px-3">Good</span>,
        <span className="word-clr me-2 p-1 px-3">Waranty</span>,
      ],

      created_on: "03-05-2022",
      decription: "lorem ipsum",
      location: 'kanpur',
      rating: '⭐⭐⭐⭐⭐',
      ratingValue: '5',
    },
    {
      id: "74",
      title: "Apple iPhone 13 Pro Max (256GB) - Sierra Blue Smart HDR 4, Night mode,",
      type: "phone",
      specification: [{ ram: "4Gb", processor: "intel core i5 3000" }],
      price: "10000",
      currency_type: "₹rupee",
      image_url:
        "https://images-eu.ssl-images-amazon.com/images/I/31tyUh1todL._SY445_SX342_QL70_FMwebp_.jpg",
      tags: [
        <span className="word-clr me-2 p-1 px-3">1Y 3M</span>,
        <span className="word-clr me-2 p-1 px-3">Good</span>,
        <span className="word-clr me-2 p-1 px-3">Waranty</span>,
      ],

      created_on: "03-05-2022",
      decription: "lorem ipsum",
      location: 'dehli',
      rating: '⭐⭐⭐',
      ratingValue: '3',
    },
    {
      id: "75",
      title: " OnePlus Nord CE 2 Lite 5G (Black Dusk, 6GB RAM, 128GB Storage)",
      type: "phone",
      specification: { ram: "4Gb", processor: "intel core i5 3000" },
      price: "10000",
      currency_type: "₹rupee",
      image_url:
        "https://images-eu.ssl-images-amazon.com/images/I/41ezRvTwcaL._SX300_SY300_QL70_FMwebp_.jpg",
      tags: [
        <span className="word-clr me-2 p-1 px-3">1Y 3M</span>,
        <span className="word-clr me-2 p-1 px-3">Good</span>,
        <span className="word-clr me-2 p-1 px-3">Waranty</span>,
      ],

      created_on: "03-05-2022",
      decription: "lorem ipsum",
      location: 'dehli',
      rating: '⭐⭐⭐',
      ratingValue: '3',
    },

    {
      id: "76",
      title: "Sony Bravia 80 cm (32 inches) HD Ready Smart LED TV ",
      type: "television",
      specification: { ram: "4Gb", processor: "intel core i5 3000" },
      price: "5000",
      currency_type: "₹rupee",
      image_url: "https://m.media-amazon.com/images/I/71vZLIfj5yS._SY450_.jpg",
      tags: [
        <span className="word-clr me-2 p-1 px-3">1Y 3M</span>,
        <span className="word-clr me-2 p-1 px-3">Good</span>,
        <span className="word-clr me-2 p-1 px-3">Waranty</span>,
      ],

      created_on: "03-05-2022",
      decription: "lorem ipsum",
      location: 'dehli',
      rating: '⭐',
      ratingValue: '1',
    },

    {
      id: "77",
      title: "LG 108 cm (43 inches) 4K Ultra HD Smart LED TV",
      type: "television",
      specification: { ram: "4Gb", processor: "intel core i5 3000" },
      price: "5000",
      currency_type: "₹rupee",
      image_url: "https://m.media-amazon.com/images/I/71k7M05go-L._SX450_.jpg",
      tags: [
        <span className="word-clr me-2 p-1 px-3">1Y 3M</span>,
        <span className="word-clr me-2 p-1 px-3">Good</span>,
        <span className="word-clr me-2 p-1 px-3">Waranty</span>,
      ],

      created_on: "03-05-2022",
      decription: "lorem ipsum",
      location: 'dehli',
      rating: '⭐⭐⭐⭐⭐',
      ratingValue: '5',
    },
    {
      id: "78",
      title: "LG 108 cm (43 inches) 4K Ultra HD Smart LED TV",
      type: "television",
      specification: { ram: "4Gb", processor: "intel core i5 3000" },
      price: "15000",
      currency_type: "₹rupee",
      image_url: "https://m.media-amazon.com/images/I/71vZLIfj5yS._SY450_.jpg",
      tags: [
        <span className="word-clr me-2 p-1 px-3">1Y 3M</span>,
        <span className="word-clr me-2 p-1 px-3">Good</span>,
        <span className="word-clr me-2 p-1 px-3">Waranty</span>,
      ],

      created_on: "03-05-2022",
      decription: "lorem ipsum",
      location: 'dehli',
      rating: '⭐⭐⭐⭐',
      ratingValue: '4',
    },
    {
      id: "79",
      title: "Samsung Galaxy S22 Ultra 5G (Burgundy, 12GB, 512GB Storage) ",
      type: "phone",
      specification: { ram: "4Gb", processor: "intel core i5 3000" },
      price: "10000",
      currency_type: "₹rupee",
      image_url:
        "https://images-eu.ssl-images-amazon.com/images/I/41ezRvTwcaL._SX300_SY300_QL70_FMwebp_.jpg",
      tags: [
        <span className="word-clr me-2 p-1 px-3">1Y 3M</span>,
        <span className="word-clr me-2 p-1 px-3">Good</span>,
        <span className="word-clr me-2 p-1 px-3">Waranty</span>,
      ],

      created_on: "03-05-2022",
      decription: "lorem ipsum",
      location: 'dehli',
      rating: '⭐⭐',
      ratingValue: '2',
    },
    {
      id: "80",
      title: "Apple iPhone 13 Pro Max (256GB) - Sierra Blue Smart HDR 4, Night mode,",
      type: "phone",
      specification: { ram: "4Gb", processor: "intel core i5 3000" },
      price: "10000",
      currency_type: "₹rupee",
      image_url:
        "https://images-eu.ssl-images-amazon.com/images/I/31sKeCe8SyL._SX300_SY300_QL70_FMwebp_.jpg",
      tags: [
        <span className="word-clr me-2 p-1 px-3">1Y 3M</span>,
        <span className="word-clr me-2 p-1 px-3">Good</span>,
        <span className="word-clr me-2 p-1 px-3">Waranty</span>,
      ],

      created_on: "03-05-2022",
      decription: "lorem ipsum",
      location: 'kanpur',
      rating: '⭐⭐⭐',
      ratingValue: '3',
    },
    {
      id: "81",
      title: " Apple iPhone 13 Pro Max (256GB) - Sierra Blue Smart HDR 4, Night mode,",
      type: "phone",
      specification: [{ ram: "4Gb", processor: "intel core i5 3000" }],
      price: "10000",
      currency_type: "₹rupee",
      image_url:
        "https://images-eu.ssl-images-amazon.com/images/I/41OBf52bnOL._SX300_SY300_QL70_FMwebp_.jpg",
      tags: [
        <span className="word-clr me-2 p-1 px-3">1Y 3M</span>,
        <span className="word-clr me-2 p-1 px-3">Good</span>,
        <span className="word-clr me-2 p-1 px-3">Waranty</span>,
      ],

      created_on: "03-05-2022",
      decription: "lorem ipsum",
      location: 'kanpur',
      rating: '⭐⭐',
      ratingValue: '2',
    },
    {
      id: "82",
      title: "OnePlus Nord CE 2 Lite 5G (Black Dusk, 6GB RAM, 128GB Storage)",
      type: "phone",
      specification: { ram: "4Gb", processor: "intel core i5 3000" },
      price: "10000",
      currency_type: "₹rupee",
      image_url: "https://m.media-amazon.com/images/I/817clKAKcqL._SX679_.jpg",
      tags: [
        <span className="word-clr me-2 p-1 px-3">1Y 3M</span>,
        <span className="word-clr me-2 p-1 px-3">Good</span>,
        <span className="word-clr me-2 p-1 px-3">Waranty</span>,
      ],

      created_on: "03-05-2022",
      decription: "lorem ipsum",
      location: 'kanpur',
      rating: '⭐⭐',
      ratingValue: '2',
    },

    {
      id: "83",
      title: "Sony Bravia 80 cm (32 inches) HD Ready Smart LED TV ",
      type: "television",
      specification: { ram: "4Gb", processor: "intel core i5 3000" },
      price: "5000",
      currency_type: "₹rupee",
      image_url: "https://m.media-amazon.com/images/I/71k7M05go-L._SX450_.jpg",
      tags: [
        <span className="word-clr me-2 p-1 px-3 ">1Y 3M</span>,
        <span className="word-clr me-2 p-1 px-3 ">Good</span>,
        <span className="word-clr me-2 p-1 px-3 ">Waranty</span>,
      ],

      created_on: "03-05-2022",
      decription: "lorem ipsum",
      location: 'kanpur',
      rating: '⭐⭐⭐⭐',
      ratingValue: '4',
    },

    {
      id: "84",
      title: "LG tv | Lorem Ipsum",
      type: "television",
      specification: { ram: "4Gb", processor: "intel core i5 3000" },
      price: "5000",
      currency_type: "₹rupee",
      image_url: "https://m.media-amazon.com/images/I/71YDOppqAzL._SX450_.jpg",
      tags: [
        <span className="word-clr me-2 p-1 px-3">1Y 3M</span>,
        <span className="word-clr me-2 p-1 px-3">Good</span>,
        <span className="word-clr me-2 p-1 px-3">Waranty</span>,
      ],

      created_on: "03-05-2022",
      decription: "lorem ipsum  ",
      location: 'kanpur',
      rating: '⭐⭐⭐⭐⭐',
      ratingValue: '5',
    },
    {
      id: "85",
      title: "LG 108 cm (43 inches) 4K Ultra HD Smart LED TV",
      type: "television",
      specification: { ram: "4Gb", processor: "intel core i5 3000" },
      price: "15000",
      currency_type: "₹rupee",
      image_url: "https://m.media-amazon.com/images/I/61V7cDH8AAS._SX569_.jpg",
      tags: [
        <span className="word-clr me-2 p-1 px-3">1Y 3M</span>,
        <span className="word-clr me-2 p-1 px-3">Good</span>,
        <span className="word-clr me-2 p-1 px-3">Waranty</span>,
      ],

      created_on: "03-05-2022",
      decription: "lorem ipsum",
      location: 'kanpur',
      rating: '⭐⭐⭐',
      ratingValue: '3',
    },
    {
      id: "86",
      title: "Dell Inspiron 5518 Laptop (11th Gen Core i5/ 16GB/ 512GB SSD/ Win10)",
      type: "laptop",
      specification: { ram: "4Gb", processor: "intel core i5 3000" },
      price: "10000",
      currency_type: "₹rupee",
      image_url: "https://m.media-amazon.com/images/I/61Dw5Z8LzJL._SL1000_.jpg",
      // 'tags' : ['today 1k','like new', 'warranty'],
      tags: [
        <span className="word-clr me-2 p-1 px-3">1D 10M</span>,
        <span className="word-clr me-2 p-1 px-3">Good</span>,
        <span className="word-clr me-2 p-1 px-3">Waranty</span>,
      ],

      created_on: "03-05-2022",
      decription: " lorem ipsum",
      location: 'kanpur',
      rating: '⭐⭐⭐⭐⭐',
      ratingValue: '5',
    },

    {
      id: "87",
      title: "HP 14s, 11th Gen Intel Core i3, 8GB RAM/512GB SSD 14-inch(35.6 cm)",
      type: "laptop",
      specification: { ram: "4Gb", processor: "intel core i5 3000" },
      price: "10000",
      currency_type: "₹rupee",
      image_url: "https://m.media-amazon.com/images/I/51UdunZimoL._SX569_.jpg",
      tags: [
        <span className="word-clr me-2 p-1 px-3">2Y 3M</span>,
        <span className="word-clr me-2 p-1 px-3">Good</span>,
        <span className="word-clr me-2 p-1 px-3">Waranty</span>,
      ],

      created_on: "03-05-2022",
      decription: "lorem ipsum",
      location: 'kanpur',
      rating: '⭐⭐⭐',
      ratingValue: '3',
    },
    {
      id: "88",
      title: "Samsung Galaxy S22 Ultra 5G (Burgundy, 12GB, 512GB Storage) ",
      type: "phone",
      specification: { ram: "4Gb", processor: "intel core i5 3000" },
      price: "10000",
      currency_type: "₹rupee",
      image_url:
        "https://images-eu.ssl-images-amazon.com/images/I/31jgoap1cQL._SY445_SX342_QL70_FMwebp_.jpg",
      tags: [
        <span className="word-clr me-2 p-1 px-3">1Y 3M</span>,
        <span className="word-clr me-2 p-1 px-3">Good</span>,
        <span className="word-clr me-2 p-1 px-3">Waranty</span>,
      ],

      created_on: "03-05-2022",
      decription: "lorem ipsum",
      location: 'kanpur',
      rating: '⭐⭐⭐',
      ratingValue: '3',
    },
    {
      id: "89",
      title: "Apple iPhone 13 Pro Max (256GB) - Sierra Blue Smart HDR 4, Night mode,",
      type: "phone",
      specification: { ram: "4Gb", processor: "intel core i5 3000" },
      price: "10000",
      currency_type: "₹rupee",
      image_url: "https://m.media-amazon.com/images/I/61-r9zOKBCL._SX679_.jpg",
      tags: [
        <span className="word-clr me-2 p-1 px-3">1Y 3M</span>,
        <span className="word-clr me-2 p-1 px-3">Good</span>,
        <span className="word-clr me-2 p-1 px-3">Waranty</span>,
      ],

      created_on: "03-05-2022",
      decription: "lorem ipsum",
      location: 'kanpur',
      rating: '⭐⭐⭐⭐⭐',
      ratingValue: '5',
    },
    
    {
      id: "90",
      title: "HP 14s, 11th Gen Intel Core i3, 8GB RAM/512GB SSD 14-inch(35.6 cm)",
      type: "laptop",
      specification: { ram: "4Gb", processor: "intel core i5 3000" },
      price: "10000",
      currency_type: "₹rupee",
      image_url: "https://m.media-amazon.com/images/I/51UdunZimoL._SX569_.jpg",
      tags: [
        <span className="word-clr me-2 p-1 px-3">2Y 3M</span>,
        <span className="word-clr me-2 p-1 px-3">Good</span>,
        <span className="word-clr me-2 p-1 px-3">Waranty</span>,
      ],

      created_on: "03-05-2022",
      decription: "lorem ipsum",
      location: 'pune',
      rating: '⭐',
      ratingValue: '1',
    },
    {
      id: "91",
      title: "Sony Bravia 80 cm (32 inches) HD Ready Smart LED TV ",
      type: "television",
      specification: { ram: "4Gb", processor: "intel core i5 3000" },
      price: "5000",
      currency_type: "₹rupee",
      image_url: "https://m.media-amazon.com/images/I/71vZLIfj5yS._SY450_.jpg",
      tags: [
        <span className="word-clr me-2 p-1 px-3">1Y 3M</span>,
        <span className="word-clr me-2 p-1 px-3">Good</span>,
        <span className="word-clr me-2 p-1 px-3">Waranty</span>,
      ],

      created_on: "03-05-2022",
      decription: "lorem ipsum",
      location: 'dehli',
      rating: '⭐⭐',
      ratingValue: '2',
    },
    {
      id: "92",
      title: "Sony Bravia 80 cm (32 inches) HD Ready Smart LED TV",
      type: "television",
      specification: { ram: "4Gb", processor: "intel core i5 3000" },
      price: "5000",
      currency_type: "₹rupee",
      image_url: "https://m.media-amazon.com/images/I/71vZLIfj5yS._SY450_.jpg",
      tags: [
        <span className="word-clr me-2 p-1 px-3">1Y 3M</span>,
        <span className="word-clr me-2 p-1 px-3">Good</span>,
        <span className="word-clr me-2 p-1 px-3">Waranty</span>,
      ],

      created_on: "03-05-2022",
      decription: "lorem ipsum",
      location: 'dehli',
      rating: '⭐⭐',
      ratingValue: '2',
    },
    {
      id: "93",
      title: "Sony Bravia 80 cm (32 inches) HD Ready Smart LED TV ",
      type: "television",
      specification: { ram: "4Gb", processor: "intel core i5 3000" },
      price: "5000",
      currency_type: "₹rupee",
      image_url: "https://m.media-amazon.com/images/I/71vZLIfj5yS._SY450_.jpg",
      tags: [
        <span className="word-clr me-2 p-1 px-3">1Y 3M</span>,
        <span className="word-clr me-2 p-1 px-3">Good</span>,
        <span className="word-clr me-2 p-1 px-3">Waranty</span>,
      ],

      created_on: "03-05-2022",
      decription: "lorem ipsum",
      location: 'dehli',
      rating: '⭐⭐',
      ratingValue: '2',
    },
    {
      id: "94",
      title: "LG 108 cm (43 inches) 4K Ultra HD Smart LED TV",
      type: "television",
      specification: { ram: "4Gb", processor: "intel core i5 3000" },
      price: "5000",
      currency_type: "₹rupee",
      image_url: "https://m.media-amazon.com/images/I/71vZLIfj5yS._SY450_.jpg",
      tags: [
        <span className="word-clr me-2 p-1 px-3">1Y 3M</span>,
        <span className="word-clr me-2 p-1 px-3">Good</span>,
        <span className="word-clr me-2 p-1 px-3">Waranty</span>,
      ],

      created_on: "03-05-2022",
      decription: "lorem ipsum",
      location: 'dehli',
      rating: '⭐⭐',
      ratingValue: '2',
    },

  ];

  export default List;